name: visualvend
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  fluttertoast: ^4.0.0
  flutter_svg: ^0.22.0

  #shared preference
  shared_preferences: ^0.5.12+4

  #credit card
  flutter_credit_card: ^0.1.4

  #badges
  badges: ^1.0.3

  #phone call
  url_launcher: ^6.0.5

  #share
  share: ^2.0.4

  equatable: ^2.0.2
  material_design_icons_flutter: ^4.0.5955

  #qrscan: ^0.2.17
  qr_code_scanner: ^0.5.2
  flutter_number_picker: ^1.0.4
  image_picker: ^0.8.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/fonts/montserrat_thin.ttf
    - assets/fonts/montserrat_light.ttf
    - assets/fonts/montserrat_regular.ttf
    - assets/fonts/montserrat_medium.ttf
    - assets/fonts/montserrat_semiBold.ttf
    - assets/fonts/montserrat_bold.ttf
    - assets/fonts/montserrat_extraBold.ttf
    - assets/fonts/montserrat_black.ttf

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat_light.ttf
          weight: 200
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 300
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 400
        - asset: assets/fonts/montserrat_semiBold.ttf
          weight: 500
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat_extraBold.ttf
          weight: 700
        - asset: assets/fonts/montserrat_black.ttf
          weight: 800

flutter_intl:
  main_locale: en_US
  enabled: true
