import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'constants.dart';

var categoryData = [
  'Drinks',
  'Snacks',
  'My Prefs',
  'Other',
];

var productListsJson = [
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_yellow.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ],
  [
    {
      'title': 'Coke',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': true,
    },
    {
      'title': 'CokeZero',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sprite',
      'icon': 'assets/icons/ic_beer_green.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Fanta',
      'icon': 'assets/icons/ic_beer_white.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Diet Coke',
      'icon': 'assets/icons/ic_beer_yellow_light.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sold Lemon',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Still Water',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Sparkling Water',
      'icon': 'assets/icons/ic_beer_black.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
    {
      'title': 'Light Sparkling',
      'icon': 'assets/icons/ic_beer.png',
      'vol': '370ml',
      'qty': '5',
      'price': '\$ 2.2',
      'item': '16',
      'failed': false,
    },
  ]
];

var mainBottomItems = [
  {
    'icon': MdiIcons.star,
    'title': 'Favorite',
    'type' : ICONTYPE.IconData,
    'shape' : 'Rect',
  },
  {
    'icon': 'assets/icons/ic_vend.svg',
    'title': 'History',
    'type' : ICONTYPE.Svg,
    'shape' : 'Rect',
  },
  {
    'icon': 'assets/icons/ic_home_btn.svg',
    'title': 'Home',
    'type' : ICONTYPE.Svg,
    'shape' : 'Rect',
  },
  {
    'icon': 'assets/icons/ic_find_nearby.svg',
    'title': 'Location',
    'type' : ICONTYPE.Svg,
    'shape' : 'Rect',
  },
  {
    'icon': MdiIcons.commentText,
    'title': 'Chat',
    'type' : ICONTYPE.IconData,
    'shape' : 'Circle',
  },
  {
    'icon': Icons.search,
    'title': 'Search',
    'type' : ICONTYPE.IconData,
    'shape' : 'Rect',
  },
];

var homeMenus = [
  {
    'title' : 'Connect to machine',
    'icon' : MdiIcons.qrcodeScan,
    'type' : ICONTYPE.IconData,
  },
  {
    'title' : 'Vend\nMenu',
    'icon' : Icons.view_module,
    'type' : ICONTYPE.IconData,
  },
  {
    'title' : 'Vend\nHistory',
    'icon' : 'assets/icons/ic_vend.svg',
    'type' : ICONTYPE.Svg,
  },
  {
    'title' : 'Personal\nSetting',
    'icon' : Icons.settings,
    'type' : ICONTYPE.IconData,
  },
];

var qrBottomItems = [
  {
    'icon': MdiIcons.arrowLeftBold,
    'title': 'Back',
    'type': ICONTYPE.IconData,
    'shape': 'Rect',
  },
  {
    'icon': 'assets/icons/ic_find_nearby.svg',
    'title': 'Nearby',
    'type': ICONTYPE.Svg,
    'shape': 'Rect',
  },
  {
    'icon': 'assets/icons/ic_home_btn.svg',
    'title': 'Home',
    'type': ICONTYPE.Svg,
    'shape': 'Rect',
  },
  {
    'icon': MdiIcons.commentText,
    'title': 'Comment',
    'type': ICONTYPE.IconData,
    'shape': 'Circle',
  },
  {
    'icon': 'assets/icons/ic_star.svg',
    'title': 'Favorite',
    'type': ICONTYPE.Svg,
    'shape': 'Rect',
  },
];

var keyBoards = [
  [
    {'title': '1', 'type': 'Text'},
    {'title': '2', 'type': 'Text'},
    {'title': '3', 'type': 'Text'},
  ],
  [
    {'title': '4', 'type': 'Text'},
    {'title': '5', 'type': 'Text'},
    {'title': '6', 'type': 'Text'},
  ],
  [
    {'title': '7', 'type': 'Text'},
    {'title': '8', 'type': 'Text'},
    {'title': '9', 'type': 'Text'},
  ],
  [
    {'title': Icons.backspace, 'type': 'Icon'},
    {'title': '0', 'type': 'Text'},
    {'title': 'OK', 'type': 'Text'},
  ],
];

var bannerData = [
  {
    'title': 'Sending Vend Request Please Wait ...',
    'type': SnackBarType.PROCESSING,
  },
  {
    'title':
    'Please Tap / Swipe / Insert Card or add Coins or Bank Notes to pay',
    'type': SnackBarType.WARING,
  },
  {
    'title': 'Vending Item Please Wait .....',
    'type': SnackBarType.PROCESSING,
  },
  {
    'title': 'Item Vend - OK Please check Tray ..',
    'type': SnackBarType.PROCESSING,
  },
  {
    'title': 'Adding this product to your cart now...',
    'type': SnackBarType.PROCESSING,
  },
  {
    'title': 'Failed to vend ...',
    'type': SnackBarType.WARING,
  },
];

var productsInCategory = [
  {
    'title': 'Coke',
    'icon': 'assets/icons/ic_beer.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': true,
  },
  {
    'title': 'CokeZero',
    'icon': 'assets/icons/ic_beer_black.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Sprite',
    'icon': 'assets/icons/ic_beer_green.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Fanta',
    'icon': 'assets/icons/ic_beer_white.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Diet Coke',
    'icon': 'assets/icons/ic_beer_yellow.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Sold Lemon',
    'icon': 'assets/icons/ic_beer_black.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Still Water',
    'icon': 'assets/icons/ic_beer_white.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Sparkling Water',
    'icon': 'assets/icons/ic_beer_yellow.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
  {
    'title': 'Light Sparkling',
    'icon': 'assets/icons/ic_beer_white.png',
    'vol': '370ml',
    'qty': '5',
    'price': '2.2',
    'item': '16',
    'failed': false,
  },
];

var vendRequestToastData = [
  {
    'title': 'Sending request to server, please Wait ...',
    'type': SnackBarType.PROCESSING,
  },
];

var machineLocations = [
  'AusGrid Top Flr',
  'Ambos Gnd Flr',
  'AMG Hornsby',
  'RPA Cent Inst',
  'Crown Casino',
  'Ambos Lwr Gr Flr',
  'AusGrid Top',
  'Ambos Gnd',
  'AMG Hornsby Flr',
  'RPA Cent Instt',
  'Crown Casinoo',
  'Ambos Lwr Gr',
];

var machineImages = [
  'assets/icons/ic_vend_1.png',
  'assets/icons/ic_vend_2.png',
  'assets/icons/ic_vend_3.png',
  'assets/icons/ic_vend_4.png',
  'assets/icons/ic_vend_5.png',
  'assets/icons/ic_vend_6.png',
  'assets/icons/ic_vend_7.png',
  'assets/icons/ic_vend_8.png',
  'assets/icons/ic_vend_9.png',
  'assets/icons/ic_vend_10.png',
  'assets/icons/ic_vend_11.png',
  'assets/icons/ic_vend_12.png',
];

String VEND_HISTORY_LAST_RECEIPTS_TITLE = 'View Last eReceipt(s)';
String VEND_HISTORY_ORDER_ITEM_TITLE = 'Vend / Order Item';
String VEND_HISTORY_ITEM_FAVORITES_TITLE = 'Add Item to Favorites';

String VEND_HISTORY_LAST_RECEIPTS_ASSET = 'assets/icons/ic_view_last.svg';
String VEND_HISTORY_ORDER_ITEM_ASSET = 'assets/icons/ic_vend_order.svg';
String VEND_HISTORY_ITEM_FAVORITES_ASSET = 'assets/icons/ic_star.svg';

String VEND_MACHINE_NEARBY_TITLE = 'Machines Nearby';
String VEND_MACHINE_BY_LOCATION_TITLE = 'By Location';
String VEND_MACHINE_FULL_LIST_TITLE = 'Full List';

String VEND_MACHINE_NEARBY_ASSET = 'assets/icons/ic_find_nearby.svg';
String VEND_MACHINE_BY_LOCATION_ASSET = 'assets/icons/ic_find_nearby.svg';
String VEND_MACHINE_FULL_LIST_ASSET = 'assets/icons/ic_more.svg';

String VEND_PRODUCT_MENU_TITLE = 'View Product Menu';
String VEND_MACHINE_LAYOUT_TITLE = 'View Machine Layout';
String VEND_MAKE_KEYBOARD_SELECTION_TITLE = 'Make Keypad Selection';

String VEND_PRODUCT_MENU_ASSET = 'assets/icons/ic_vend_select.svg';
String VEND_MACHINE_LAYOUT_ASSET = 'assets/icons/ic_view_product.svg';
String VEND_MAKE_KEYBOARD_SELECTION_ASSET = 'assets/icons/ic_manul.svg';

String VEND_FAVORITE_MMACHINES_TITLE = 'Favorite Machines';
String VEND_FAVORITE_PRODUCTS_TITLE = 'Favorite Products';

String VEND_FAVORITE_MMACHINES_ASSET = 'assets/icons/ic_find_nearby.svg';
String VEND_FAVORITE_PRODUCTS_ASSET = 'assets/icons/ic_view_product.svg';
